apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environments
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: "preyashyadav"
          repo: "ProdPreview"
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: "pr-{{number}}-prod-preview"
    spec:
      project: default
      source:
        repoURL: "https://github.com/preyashyadav/ProdPreview.git"
        targetRevision: "{{head_sha}}"
        path: deploy/helm/app
        helm:
          valueFiles:
            - values-preview.yaml
          parameters:
            - name: api.image.tag
              value: "{{head_sha}}"
            - name: frontend.image.tag
              value: "{{head_sha}}"
            - name: worker.image.tag
              value: "{{head_sha}}"
            - name: worker.apiUrl
              value: "http://pr-{{number}}-prod-preview-api:4000/api/hello"
      destination:
        server: https://kubernetes.default.svc
        namespace: "pr-{{number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
