# infra/helm/api-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "api-chart.selectorLabels" . | nindent 4 }}
