global:
  imageTag: "latest"

api:
  image:
    repository: "preyashyadav/prod-preview-api"
    tag: "latest"

frontend:
  image:
    repository: "preyashyadav/prod-preview-frontend"
    tag: "latest"

worker:
  image:
    repository: "preyashyadav/prod-preview-worker"
    tag: "latest"
  apiUrl: "http://{{ .Release.Name }}-api:4000/api/hello"
